AlquilerVehiculos/Models/ErrorViewModel.cs
namespace AlquilerVehiculos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlquilerVehiculos/Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerVehiculos.Controllers
{
    public class AdminController : Controller
    {
        // GET: AdminController
        public ActionResult Admin()
        {
            return View();
        }

        
    }
}

AlquilerVehiculos/Controllers/ClientesController.cs
using capaDatos;
using capaEntidad;
using capaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerVehiculos.Controllers
{
    public class ClientesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public List<ClientesCLS> listarClientes()
        {
            ClientesDAL obj = new ClientesDAL();
            return obj.listarClientes();
        }
        public int GuardarCliente(ClientesCLS cliente)
        {
            ClientesBL obj = new ClientesBL();
            return obj.GuardarCliente(cliente);
        }
        public ClientesCLS RecuperarCliente(int idCliente)
        {
            ClientesBL obj = new ClientesBL();

            ClientesCLS cliente = obj.RecuperarCliente(idCliente);
            return cliente;
        }
    }
}

AlquilerVehiculos/Controllers/EmpleadosController.cs
using capaDatos;
using capaEntidad;
using capaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerVehiculos.Controllers
{
    public class EmpleadosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public List<EmpleadosCLS> listarEmpleados()
        {
            EmpleadosDAL obj = new EmpleadosDAL();
            return obj.listarEmpleados();
        }
        public int GuardarEmpleado(EmpleadosCLS empleado )
        {
            EmpleadosBL obj = new EmpleadosBL();
            return obj.GuardarEmpleado(empleado);
        }
        public EmpleadosCLS RecuperarEmpleado(int idEmpleado)
        {
            EmpleadosBL obj = new EmpleadosBL();
            
            EmpleadosCLS empleados = obj.RecuperarEmpleado(idEmpleado);
            return empleados;
        }
        public int EliminarEmpleado(int idEmpleado)
        {
            EmpleadosBL obj = new EmpleadosBL();
            return obj.EliminarEmpleado(idEmpleado);
        }
    }
}

AlquilerVehiculos/Controllers/HomeController.cs
using System.Diagnostics;
using AlquilerVehiculos.Models;
using Microsoft.AspNetCore.Mvc;
using AlquilerVehiculos.Models;

namespace AlquilerVehiculos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
     
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AlquilerVehiculos/Controllers/InicioSesionController.cs
using capaEntidad;
using capaNegocio;
using Microsoft.AspNetCore.Mvc;
namespace AlquilerVehiculos.Controllers
{
    public class InicioSesionController : Controller
    {
        public IActionResult InicioSesion()
        {
            return View();
        }

        public int Registrar(ClientesCLS usuario)
        {
            ClientesBL cliente = new ClientesBL(); 
            return cliente.Registrar(usuario);
        }


        public int Validar(ClientesCLS usuario)
        {
            ClientesBL cliente = new ClientesBL();
            return cliente.ValidarUsuario(usuario);
        }

    }
}

AlquilerVehiculos/Controllers/PagosController.cs
using capaDatos;
using capaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerVehiculos.Controllers
{
    public class PagosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public List<PagosCLS> listarPagos()
        {
            PagosDAL obj = new PagosDAL();
            return obj.listarPagos();
        }
    }
}

AlquilerVehiculos/Controllers/ReservasController.cs
using capaDatos;
using capaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerVehiculos.Controllers
{
    public class ReservasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public List<ReservasCLS> listarReservas()
        {
            ReservasDAL obj = new ReservasDAL();
            return obj.listarReservas();
        }
    }
}

AlquilerVehiculos/Controllers/SegurosController.cs
using capaDatos;
using capaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerVehiculos.Controllers
{
    public class SegurosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Basico()
        {
            return View();
        }
        public IActionResult Intermedio()
        {
            return View();
        }
        public IActionResult Premium()
        {
            return View();
        }
        public List<SegurosCLS> listarSeguros()
        {
            SegurosDAL obj = new SegurosDAL();
            return obj.listarSeguros();
        }
    }
}

AlquilerVehiculos/Controllers/VehiculosController.cs
using capaDatos;
using capaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace AlquilerVehiculos.Controllers
{
    public class VehiculosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public List<VehiculosCLS> listarVehiculos()
        {
            VehiculosDAL obj = new VehiculosDAL();
            return obj.listarVehiculos();
        }
    }
}

AlquilerVehiculos/Views/Admin/Admin.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Inicio - Empleado";
}

<h1>Bienvenido, Empleado</h1>
<p>Esta es la página de inicio del administrador.</p>

AlquilerVehiculos/Views/Clientes/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Clientes - Empleados";
}
<h1>Clientes</h1>


<button type="button" class="btn btn-success" data-bs-toggle="modal" onclick="MostrarModal()">
    Nuevo Cliente
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-briefcase" viewBox="0 0 16 16">
        <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v8A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5m1.886 6.914L15 7.151V12.5a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5V7.15l6.614 1.764a1.5 1.5 0 0 0 .772 0M1.5 4h13a.5.5 0 0 1 .5.5v1.616L8.129 7.948a.5.5 0 0 1-.258 0L1 6.116V4.5a.5.5 0 0 1 .5-.5" />
    </svg>
</button>

<br />
<br />


<!-- Modal -->
<div class="modal fade" id="modalCliente" tabindex="-1" aria-labelledby="modalClienteLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalClienteLabel">Gestionar Cliente</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmCliente" method="post" class="row g-3">
                    <div class="col-md-4">
                        <label for="inputIdCliente" class="form-label">Id Cliente</label>
                        <input type="text" class="form-control shadow-sm rounded" name="idCliente" id="idCliente" readonly>
                    </div>
                    <div class="col-md-4">
                        <label for="inputIdUsuario" class="form-label">Id Usuario</label>
                        <input type="text" class="form-control shadow-sm rounded" name="idUsuario" id="idUsuario" readonly>
                    </div>
                    <div class="col-md-4">
                        <label for="inputNombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control shadow-sm rounded" name="nombre" id="nombre">
                    </div>
                    <div class="col-md-4">
                        <label for="inputApellido" class="form-label">Apellido</label>
                        <input type="text" class="form-control shadow-sm rounded" name="apellido" id="apellido">
                    </div>
                    <div class="col-md-4">
                        <label for="inputNombreUsuario" class="form-label">Nombre Usuario</label>
                        <input type="text" class="form-control shadow-sm rounded" name="nombreUsuario" id="nombreUsuario">
                    </div>
                    <div class="col-md-4">
                        <label for="inputEmail" class="form-label">Email</label>
                        <input type="text" class="form-control shadow-sm rounded" name="email" id="email">
                    </div>
                    <div class="col-md-4">
                        <label for="inputTelefono" class="form-label">Telefono</label>
                        <input type="text" class="form-control shadow-sm rounded" name="telefono" id="telefono">
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="GuardarCliente()">Guardar</button>
                <button type="button" class="btn btn-secondary" onclick="LimpiarCliente()">Limpiar</button>
            </div>
        </div>
    </div>
</div>


<div id="divTabla"></div>

<script src="~/js/clientes.js"></script>
<script src="~/js/generic.js"></script>

AlquilerVehiculos/Views/Empleados/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Empleados - Empleados";
}


<h1>Empleados</h1>

<button type="button" class="btn btn-success" data-bs-toggle="modal" onclick="MostrarModal()">
    Nuevo Empleado
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-briefcase" viewBox="0 0 16 16">
        <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v8A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5m1.886 6.914L15 7.151V12.5a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5V7.15l6.614 1.764a1.5 1.5 0 0 0 .772 0M1.5 4h13a.5.5 0 0 1 .5.5v1.616L8.129 7.948a.5.5 0 0 1-.258 0L1 6.116V4.5a.5.5 0 0 1 .5-.5" />
    </svg>
</button>

<br />
<br />


<!-- Modal -->
<div class="modal fade" id="modalEmpleado" tabindex="-1" aria-labelledby="modalEmpleadoLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalEmpleadoLabel">Gestionar Empleado</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmEmpleado" method="post" class="row g-3">
                    <div class="col-md-4">
                        <label for="inputIdEmpleado" class="form-label">Id Empleado</label>
                        <input type="text" class="form-control shadow-sm rounded" name="idEmpleado" id="idEmpleado"  readonly>
                    </div>
                    <div class="col-md-4">
                        <label for="inputIdUsuario" class="form-label">Id Usuario</label>
                        <input type="text" class="form-control shadow-sm rounded" name="idUsuario" id="idUsuario" readonly>
                    </div>
                    <div class="col-md-4">
                        <label for="inputNombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control shadow-sm rounded" name="nombre" id="nombre">
                    </div>
                    <div class="col-md-4">
                        <label for="inputApellido" class="form-label">Apellido</label>
                        <input type="text" class="form-control shadow-sm rounded" name="apellido" id="apellido">
                    </div>
                    <div class="col-md-4">
                        <label for="inputEmail" class="form-label">Email</label>
                        <input type="text" class="form-control shadow-sm rounded" name="email" id="email">
                    </div>
                    <div class="col-md-4">
                        <label for="inputCargo" class="form-label">Cargo</label>
                        <select class="form-select shadow-sm rounded" name="cargo" id="cargo">
                            <option value="">Seleccione un cargo</option>
                            <option value="Administrativo">Administrativo</option>
                            <option value="Operativo">Operativo</option>
                            <option value="Atencion al Cliente y Ventas">Atención al Cliente y Ventas</option>
                            <option value="Logistica">Logística</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="inputTelefono" class="form-label">Telefono</label>
                        <input type="text" class="form-control shadow-sm rounded" name="telefono" id="telefono">
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="GuardarEmpleado()">Guardar</button>
                <button type="button" class="btn btn-secondary" onclick="LimpiarEmpleados()">Limpiar</button>
            </div>
        </div>
    </div>
</div>



<div id="divTabla"></div>
<script src="~/js/empleados.js"></script>
<script src="~/js/generic.js"></script>

AlquilerVehiculos/Views/InicioSesion/InicioSesion.cshtml
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0">
    <link rel="stylesheet" href="https://raw.githubusercontent.com/Ahmed-Massoud/Login-and-sign-up-form/main/font.css">
    <link rel="stylesheet" href="~/css/SingUp.css" asp-append-version="true">

</head>

    <div id="containerSingUp">

        <div class="main" id="main">

            <input type="checkbox" id="chk">

            <div class="signup"  >
                <label for="chk" class="sig">Registrarse</label>
                <div class="form-row">
                    <div class="user-box">
                        <input type="text" title="Ingresar nombre" id="nombre" name="nombre" required autocomplete="off">
                        <label id="nameLabel">Nombre</label>
                        <img src="https://raw.githubusercontent.com/Ahmed-Massoud/Login-and-sign-up-form/main/logo.svg" alt="Logo" class="logo-img" id="nameIcon">
                    </div>

                    <div class="user-box">
                        <input type="text" title="Ingresar apellido" id="apellido" name="apellido" required autocomplete="off">
                        <label id="lasnameLabel">Apellido</label>
                        <img src="https://raw.githubusercontent.com/Ahmed-Massoud/Login-and-sign-up-form/main/logo.svg" alt="Logo" class="logo-img" id="lastNameIcon">
                    </div>
                </div>

                <div class="form-row">
                    <div class="user-box">
                        <input type="text" title="Ingresar nombre usuario" id="nombreUsuario" name="nombreUsuario" required autocomplete="off">
                        <label id="usernameLabel">Nombre de Usuario</label>
                        <img src="https://raw.githubusercontent.com/Ahmed-Massoud/Login-and-sign-up-form/main/logo.svg" alt="Logo" class="logo-img" id="userIcon">
                    </div>

                    <div class="user-box">
                        <input type="text" title="Ingresar telefono" id="telefono" name="telefono" required autocomplete="off">
                        <label id="telephoneLabel">Teléfono</label>
                        <img src="https://raw.githubusercontent.com/Ahmed-Massoud/Login-and-sign-up-form/main/logo.svg" alt="Logo" class="logo-img" id="telephoneIcon">
                    </div>
                </div>

                <div class="form-row">
                    <div class="user-box">
                        <input type="text" title="Ingresar email" id="email" name="email" required autocomplete="off">
                        <label id="emailLabel">Email</label>
                        <img src="https://raw.githubusercontent.com/Ahmed-Massoud/Login-and-sign-up-form/main/logo.svg" alt="Logo" class="logo-img" id="emailIcon">
                    </div>

                    <div class="user-box">
                        <input type="password" title="Ingresar contraseña" id="contraseña" name="contraseña" required autocomplete="off">
                        <label id="passwordLabel">Contraseña</label>
                        <img src="https://raw.githubusercontent.com/Ahmed-Massoud/Login-and-sign-up-form/main/logo.svg" alt="Logo" class="logo-img" id="passIcon">
                    </div>
                </div>

            
                <button onclick="Registrar()" id="button" class="btnLogIn">Registrarse</button>
            </div>

            <div class=" login"  >

                <label for="chk" class="log">Inicio Sesion</label>

                <div class="user-box">

                    <input type="text" title="Ingresar nombre usuario" id="nombreUsuario2" name="nombreUsuario" required>

                    <label>Username</label>

                </div>

                <div class="user-box">

                    <input type="password" title="Ingresar contraseña" id="contraseña2" name="contraseña" required>

                    <label>Password</label>

                </div>
                <button onclick="ValidarInicioSesion()" id="button2" class="btnLogIn">Iniciar Sesion</button>

            </div>

        </div>

    </div>

<script src="~/js/singup.js"></script>
<script src="~/js/generic.js"></script>

AlquilerVehiculos/Views/Pagos/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Pagos</h1>

<div id="divtabla"></div>

<script src="~/js/pagos.js"></script>
<script src="~/js/generic.js"></script>

AlquilerVehiculos/Views/Reservas/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Reservas</h1>

<div id="divtabla"></div>

<script src="~/js/reservas.js"></script>
<script src="~/js/generic.js"></script>

AlquilerVehiculos/Views/Seguros/Basico.cshtml
@{
    ViewData["Title"] = "Basico";
}

<section class="seguro-basico" id="seguro-basico">
    <div class="text-container-seguro-basico">
        <h3>Seguro Basico</h3>
    </div>
</section>
<br />
<body class="cuerpoPagina-seguros">
    <section class="intro">
        <p>¿Qué incluye el Seguro Básico?</p>
    </section>
    <section class="seguros-container">
            <div class="card-seguros">
                <div class="content-seguros">
                    <p class="heading">Responsabilidad Civil</p>
                    <i class="fas fa-shield-alt"></i>
                    <p class="para">
                        Cubre daños a terceros en caso de accidente.
                    </p>
                </div>
            </div>
            <div class="card-seguros">
                <div class="content-seguros">
                    <p class="heading">Protección contra Robo</p>
                    <i class="fas fa-car"></i>
                    <p class="para">
                        Seguridad en caso de robo o intento de hurto.
                    </p>
                </div>
            </div>
    </section>
</body>
<br />
<br />
<br />

AlquilerVehiculos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlquilerVehiculos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="//cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="//cdn.datatables.net/2.2.2/js/dataTables.min.js"></script>
</head>

<body>
    <header class="header">

        <div id="menu-btn" class="fas fa-bars"></div>

        <a href="../" class="logo">
            <span>Driv</span>Go 
        </a>
        <nav class="navbar">
        <a class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </a>
        <a class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Vehiculos" asp-action="Index">Vehiculos</a>
        </a>
            <div class="nav-item dropdown">
                <a class="nav-link text-dark dropbtn" href="/Seguros">Seguros ▾</a>
                <ul class="dropdown-content">
                    <li><a asp-area="" asp-controller="Seguros" asp-action="Basico">Seguro Basico</a></li>
                    <li><a asp-area="" asp-controller="Seguros" asp-action="Intermedio">Seguro Intermedio</a></li>
                    <li><a asp-area="" asp-controller="Seguros" asp-action="Premium">Seguro Premium</a></li>
                </ul>
            </div>
        <a class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </a>
        </nav>

        <div id="login-btn">
            <a href="/InicioSesion/InicioSesion" class="btn">Login</a>
            <i class="far fa-user"></i>
        </div>


    </header>

    <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="box-container">
            <div class="box">
                <h3>Sucursales</h3>
                <a href="https://maps.app.goo.gl/X3iaUb2omEWneXfx7" target="_blank"> <i class="fas fa-map-marker-alt"></i>Sangolqui - Ecuador </a>
            </div>
            <div class="box">
                <h3>Informacion de Contacto</h3>
                <a href="https://wa.me/message/5BYYLRCUIQBEB1" target="_blank"> <i class="fas fa-phone"></i> +593 99 097 9587 </a>
                <a href="mailto:drivgo@gmail.com"> <i class="fas fa-envelope"></i> drivgo@gmail.com </a>
                <a href="https://maps.app.goo.gl/X3iaUb2omEWneXfx7" target="_blank"> <i class="fas fa-map-marker-alt"></i> Ecuador - Sangolqui 17707 </a>
            </div>

            <div class="box">
                <h3>‎</h3>
                <a href="https://www.facebook.com/?locale=es_LA" target="_blank"> <i class="fab fa-facebook-f"></i> Facebook </a>
                <a href="https://x.com/?lang=es" target="_blank"> <i class="fab fa-twitter"></i> Twitter </a>
                <a href="https://wa.me/message/5BYYLRCUIQBEB1" target="_blank"> <i class="fab fa-whatsapp"></i> Whatsapp </a>
                <a href="https://www.instagram.com/" target="_blank"> <i class="fab fa-instagram"></i> Instagram </a>
            </div>

        </div>

        <div class="credit">&copy; 2025 - AlquilerVehiculos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js"></script>
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AlquilerVehiculos/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin - @ViewBag.Title</title>
    <link href="~/css/AdminStyle.css" rel="stylesheet" />
    <!-- CSS de Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Toastr CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />

    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />
</head>
<body>
    <!-- Barra de navegación lateral -->
    <aside class="sidebar">
        <nav class="navbar">
            <ul>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                </li>
            </ul>
        </nav>
    </aside>

    <!-- Contenido principal -->
    <main class="main-content">
        <header class="header">
            <h1>Panel Empleados</h1>
        </header>
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <!-- Footer -->
    <footer class="footer">
        <p>&copy; @DateTime.Now.Year - Administración</p>
    </footer>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>

    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Toastr JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>


</body>
</html>

AlquilerVehiculos/Views/Vehiculos/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<body class="cuerpoPagina">
    <h1>Vehiculos</h1>
    <div id="vehicles-container"></div>
</body>


<script src="~/js/vehiculos.js"></script>
<script src="~/js/generic.js"></script>